{
 "title": "MongoDB Instance",
 "tags": [ "mongodb-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(mongodb_up,job)" } },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(mongodb_up{job=~\"$job\"},cluster)"
    }
   },
   {
    "name": "mongodb_cluster",
    "label": "mongodb_cluster",
    "query": {
     "query": "label_values(mongodb_up{job=~\"$job\", cluster=~\"$cluster\"},mongodb_cluster)"
    }
   },
   {
    "name": "service_name",
    "label": "service name",
    "query": {
     "query": "label_values(mongodb_up{job=~\"$job\", cluster=~\"$cluster\", mongodb_cluster=~\"$mongodb_cluster\"}, service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_instance_uptime_seconds{service_name=~\"$service_name\", cluster=~\"$cluster\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\",type!=\"command\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) or irate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "ReplSet",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_my_state{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service_name) (irate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) / (irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) > 0))"
    }
   ]
  },
  {
   "title": "Current ReplSet State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_my_state{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Service Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Command Operations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (service_name, type) (irate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type!=\"command\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) or  irate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type!=\"command\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg by (service_name, type) (irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type!~\"(command|query|getmore)\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) or irate(mongodb_mongos_op_counters_repl_total{service_name=~\"$service_name\", type!~\"(command|query|getmore)\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "avg by (service_name) (irate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) or irate(mongodb_mongos_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "ttl_delete"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_mongod_connections{service_name=~\"$service_name\", state=\"current\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"} or mongodb_mongos_connections{service_name=~\"$service_name\", state=\"current\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"} or mongodb_connections{service_name=~\"$service_name\", state=\"current\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (service_name,state) (irate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Latency Detail",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (service_name,type) (irate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) / (irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) > 0))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (service_name,type) (mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (service_name,state) (mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"} or mongodb_mongod_cursors{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"} or mongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"} or  mongodb_mongos_cursors{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (service_name,state) (irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_record_moves_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "Assert Events",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (service_name,type) (irate(mongodb_mongod_asserts_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) or irate(mongodb_mongos_asserts_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) or irate(mongodb_asserts_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "getLastError Write Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (service_name) (irate(mongodb_mongod_metrics_get_last_error_wtime_num_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) or irate(mongodb_mongos_metrics_get_last_error_wtime_num_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "avg by (service_name) (irate(mongodb_mongod_metrics_get_last_error_wtimeouts_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) or irate(mongodb_mongos_metrics_get_last_error_wtimeouts_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Timeouts"
    }
   ]
  },
  {
   "title": "Query Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))/ sum(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Document"
    },
    {
     "expr": "sum(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))/ sum(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Index"
    }
   ]
  },
  {
   "title": "getLastError Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (service_name) (irate(mongodb_mongod_metrics_get_last_error_wtime_total_milliseconds{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) or irate(mongodb_mongos_metrics_get_last_error_wtime_total_milliseconds{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Write Wait Time"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (service_name) (irate(mongodb_mongod_extra_info_page_faults_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) or irate(mongodb_mongos_extra_info_page_faults_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]) or irate(mongodb_extra_info_page_faults_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Faults"
    }
   ]
  }
 ]
}