{
 "title": "MongoDB ReplicaSet",
 "tags": [ "mongodb-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(mongodb_up,job)" } },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(mongodb_up{job=~\"$job\"},cluster)"
    }
   },
   {
    "name": "mongodb_cluster",
    "label": "mongodb_cluster",
    "query": {
     "query": "label_values(mongodb_up{job=~\"$job\", cluster=~\"$cluster\"},mongodb_cluster)"
    }
   },
   {
    "name": "replset",
    "label": "replica set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{job=~\"$job\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\"}, set)"
    }
   },
   {
    "name": "service_name",
    "label": "service name",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{job=~\"$job\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\", set=\"$replset\"}, service_name)"
    }
   },
   {
    "name": "secondary",
    "query": {
     "query": "query_result(mongodb_mongod_replset_my_state{job=~\"$job\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\", set=\"$replset\"}==2)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ReplSet Members",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (set) (mongodb_mongod_replset_number_of_members{set=~\"$replset\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\", service_name=~\"$service_name\"} or mongodb_mongod_replset_my_state{set=~\"$replset\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\", service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(mongodb_mongod_replset_member_election_date{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Avg ReplSet Lag",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (set) (max_over_time(mongodb_mongod_replset_member_replication_lag{set=\"$replset\",service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[${__range}]))"
    }
   ]
  },
  {
   "title": "MongoDB Versions",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "avg by (service_name, mongodb_cluster, mongodb) (mongodb_version_info{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "ReplSet States",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (set, mongodb_cluter, service_name) (mongodb_mongod_replset_my_state{set=~\"$replset\",service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (name) (max(max_over_time(mongodb_mongod_replset_member_replication_lag{set=\"$replset\",service_name=~\"$secondary\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval])) by (name, service_name,set,mongodb_cluster))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Operations - $service_name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (service_name,type) (irate(mongodb_op_counters_repl_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "repl - {{type}}"
    },
    {
     "expr": "avg by (service_name,type) (irate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "repl - {{type}}"
    },
    {
     "expr": "avg by (service_name,type) (irate(mongodb_op_counters_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Elections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "max by (service_name) (changes(mongodb_mongod_replset_member_election_date{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Max Heartbeat Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - avg by (service_name) (max(mongodb_mongod_replset_member_last_heartbeat{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}) by (name)) * on (name) group_right avg by (service_name) (mongodb_mongod_replset_my_name{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Max Member Ping Time - $service_name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (service_name,name,state) (mongodb_mongod_replset_member_ping_ms{set=~\"$replset\",service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"} or label_replace(label_replace(mongodb_rs_members_pingMs{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\", member_state!=\"\"},\"state\", \"$1\", \"member_state\", \"(.*)\"),\"name\", \"$1\", \"member_idx\", \"(.*)\"))",
     "legendFormat": "{{service_name}} - {{name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Oplog Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Oplog Buffered Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (service_name) (mongodb_mongod_metrics_repl_buffer_count{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Oplog Getmore Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (service_name) (irate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Oplog Recovery Window - $service_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time()-avg by (service_name) (mongodb_mongod_replset_oplog_tail_timestamp{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"})",
     "legendFormat": "Now to End"
    },
    {
     "expr": "avg by (service_name) (mongodb_mongod_replset_oplog_head_timestamp{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}-mongodb_mongod_replset_oplog_tail_timestamp{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"})",
     "legendFormat": "Oplog Range"
    }
   ]
  },
  {
   "title": "Oplog Processing Time - $service_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (service_name) (irate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "avg by (service_name) (irate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "avg by (service_name) (irate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Operations - $service_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "repeat": "service_name",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (service_name) (irate(mongodb_mongod_metrics_repl_preload_docs_num_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "avg by (service_name) (irate(mongodb_mongod_metrics_repl_preload_indexes_num_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "avg by (service_name) (irate(mongodb_mongod_metrics_repl_apply_ops_total{service_name=~\"$service_name\", cluster=~\"$cluster\", mongodb_cluster=\"$mongodb_cluster\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Batch Apply"
    }
   ]
  }
 ]
}